# Generated by Django 4.2.2 on 2023-06-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0005_farm_water_pump'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='water_pump',
        ),
    ]
